### ISSUE TITLE
Outputs

### ISSUE THREAD

**Issue by ValeriKehayov** [mineiros-io/terraform-aws-iam-role#24]
Hi, 

The module is working fine, everything is created and all is ok. 
But I am unable to output instanceProfileName, could you please explain how outputs works?

**Comment by mariux** [comment]
Hi @ValeriKehayov,

if you used and created an instance profile along with creating the role like this:

```terraform
module "myname" {
  source  = "mineiros-io/iam-role/aws"
  version = "~> 0.4.0"

  ...
  create_instance_profile = true
  ...

}
```

the instance profile name should be in the instance profiles object in the outputs: `module.myname.instance_profile.name`.

Please let us know if this answers your question.

**Comment by ValeriKehayov** [comment]
Hi, 
Many thanks, that worked.
```output "instance_profile" {
  description = "The aws_iam_instance_profile object."
  value       = module.instance_profile_s3_transline_bucket_access.instance_profile.name
}
```
I was missing .instance_profile. in the value.
![image](https://user-images.githubusercontent.com/79916444/110425467-1120ec80-80ad-11eb-9055-abc8bde86186.png)

Keep up the great work.
Best Regards
Valeri Kehayov - ITGix ltd
https://itgix.com/
